FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    DAGSTER_HOME=/opt/dagster/dagster_home/

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install \
    dagster==1.13.20 \
    dagster-webserver==1.13.20 \
    dagster-postgres>=0.29.0 \
    dagster-graphql==1.13.20

RUN mkdir -p $DAGSTER_HOME

COPY dagster_home/dagster.yaml dagster_home/workspace.yaml $DAGSTER_HOME/

WORKDIR $DAGSTER_HOME

EXPOSE 3000
