[pytest]
DJANGO_SETTINGS_MODULE = ReadAndQues.settings.dev
python_files = test_*.py *_test.py
pythonpath = . ReadAndQues
testpaths = ReadAndQues/service/tests ReadAndQues/readspace/tests ReadAndQues/accounts/tests
addopts = --tb=short -ra
