# Generated by Django 6.0.7 on 2026-08-04 08:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleImportRequest",
            fields=[
                ("request_id", models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("url", models.CharField(max_length=1024)),
                ("article_id", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("stars_charged", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "service_article_import_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttemptLog",
            fields=[
                ("attempt_id", models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("article_id", models.CharField(max_length=64)),
                ("score", models.IntegerField(default=0)),
                ("total_questions", models.IntegerField(default=0)),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("highlighted_markdown", models.TextField(blank=True, default="")),
                ("elapsed_time", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "service_exam_attempt_log",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
